// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3llmADBrj_mihqNqBGtuboLwjFMxQc1Q',
    appId: '1:1094459505106:web:825d02e5fd1e14c050f00b',
    messagingSenderId: '1094459505106',
    projectId: 'aplikasifasum',
    authDomain: 'aplikasifasum.firebaseapp.com',
    storageBucket: 'aplikasifasum.appspot.com',
    measurementId: 'G-W2E2N5RLKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArrtD1N3Ib5g7Z6S1y0K7v-regl5yrTDA',
    appId: '1:1094459505106:android:be620631427aecac50f00b',
    messagingSenderId: '1094459505106',
    projectId: 'aplikasifasum',
    storageBucket: 'aplikasifasum.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK5jXFVfSNYzZaZqCymPapKeXAeBl6AMc',
    appId: '1:1094459505106:ios:f6a39b1537c4151350f00b',
    messagingSenderId: '1094459505106',
    projectId: 'aplikasifasum',
    storageBucket: 'aplikasifasum.appspot.com',
    iosBundleId: 'com.example.aplikasiFasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK5jXFVfSNYzZaZqCymPapKeXAeBl6AMc',
    appId: '1:1094459505106:ios:f6a39b1537c4151350f00b',
    messagingSenderId: '1094459505106',
    projectId: 'aplikasifasum',
    storageBucket: 'aplikasifasum.appspot.com',
    iosBundleId: 'com.example.aplikasiFasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3llmADBrj_mihqNqBGtuboLwjFMxQc1Q',
    appId: '1:1094459505106:web:3d6890fcbdf89df950f00b',
    messagingSenderId: '1094459505106',
    projectId: 'aplikasifasum',
    authDomain: 'aplikasifasum.firebaseapp.com',
    storageBucket: 'aplikasifasum.appspot.com',
    measurementId: 'G-F8GLWM4X6W',
  );
}
